# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Telemetry-source config generation for the #324 admin bootstrap.

Pure functions: a validated :class:`BootstrapSpec` (signal tier + privacy
tier + receiver coordinates) in, deployable artifacts out. No GCP calls —
the orchestration that deploys the receiver and fills in the real endpoint
/ token lives in the ``bqaa-otel bootstrap`` command (PR 2).

Tier semantics (issue #324 + the receiver design doc):

* ``baseline`` (default) — logs + metrics only. No prompt text, no raw API
  bodies, no tool output content.
* ``security-audit`` — adds tool/MCP/Bash decision detail
  (``OTEL_LOG_TOOL_DETAILS``) where the product exposes that control.
* ``replay`` — adds prompt capture (``OTEL_LOG_USER_PROMPTS``); requires an
  explicit acknowledgement because prompt text can contain full conversation
  history. Raw API *bodies* are a separate deferred fast-follow and are not
  promised here. Codex is never offered replay: it documents no supported
  raw request/response body path.

Codex metrics/trace exporter config is version-specific and stays gated
(``"none"``) until #317 pins and verifies the concrete config shape.
"""

from __future__ import annotations

import dataclasses
import json

PRIVACY_TIERS = ("baseline", "security-audit", "replay")
SIGNALS = ("logs", "metrics", "traces")
# Issue #324 defines exactly two signal tiers. Partial subsets are rejected
# rather than partially honored (a "logs-only" config would still enable the
# metrics exporter, which is worse than an early error).
SIGNAL_TIERS = (
    frozenset(("logs", "metrics")),
    frozenset(("logs", "metrics", "traces")),
)
SOURCES = ("claude-code", "codex")

_TOKEN_PLACEHOLDER = "<token>"


@dataclasses.dataclass(frozen=True)
class BootstrapSpec:
  """Validated admin choices that drive config generation."""

  endpoint: str
  signals: tuple[str, ...] = ("logs", "metrics")
  privacy: str = "baseline"
  token: str | None = None
  resource_attributes: dict[str, str] | None = None
  acknowledge_content_logging: bool = False

  def __post_init__(self):
    if self.privacy not in PRIVACY_TIERS:
      raise ValueError(
          f"unknown privacy tier {self.privacy!r}; expected one of"
          f" {PRIVACY_TIERS}"
      )
    for s in self.signals:
      if s not in SIGNALS:
        raise ValueError(f"unknown signal {s!r}; expected one of {SIGNALS}")
    if frozenset(self.signals) not in SIGNAL_TIERS:
      raise ValueError(
          f"unsupported signal tier {','.join(self.signals)!r}; expected"
          " 'logs,metrics' or 'logs,metrics,traces'"
      )
    if self.privacy == "replay" and not self.acknowledge_content_logging:
      raise ValueError(
          "privacy tier 'replay' enables prompt/content logging and"
          " requires acknowledge_content_logging=True"
          " (--i-understand-content-logging)"
      )

  @property
  def bearer(self) -> str:
    return self.token if self.token is not None else _TOKEN_PLACEHOLDER


def claude_code_managed_settings(spec: BootstrapSpec) -> dict:
  """Claude Code managed-settings JSON body for the chosen tiers."""
  env = {
      "CLAUDE_CODE_ENABLE_TELEMETRY": "1",
      "OTEL_LOGS_EXPORTER": "otlp",
      "OTEL_METRICS_EXPORTER": "otlp",
      "OTEL_EXPORTER_OTLP_PROTOCOL": "http/protobuf",
      "OTEL_EXPORTER_OTLP_ENDPOINT": spec.endpoint,
      "OTEL_EXPORTER_OTLP_HEADERS": f"Authorization=Bearer {spec.bearer}",
  }
  if "traces" in spec.signals:
    # Tracing needs the enhanced-telemetry beta flag in addition to the
    # exporter; exporter-only config looks enabled but emits no spans.
    env["OTEL_TRACES_EXPORTER"] = "otlp"
    env["CLAUDE_CODE_ENHANCED_TELEMETRY_BETA"] = "1"
  if spec.privacy in ("security-audit", "replay"):
    env["OTEL_LOG_TOOL_DETAILS"] = "1"
  if spec.privacy == "replay":
    env["OTEL_LOG_USER_PROMPTS"] = "1"
  if spec.resource_attributes:
    env["OTEL_RESOURCE_ATTRIBUTES"] = ",".join(
        f"{k}={v}" for k, v in spec.resource_attributes.items()
    )
  return {"env": env}


def codex_config_toml(spec: BootstrapSpec) -> str:
  """Codex ``~/.codex/config.toml`` template for the chosen tiers.

  Logs-only until #317 verifies the version-specific metrics/trace exporter
  shape; prompt capture is never enabled (Codex documents no supported raw
  request/response body path, so replay is not offered).
  """
  lines = [
      "# Generated by bqaa-otel (issue #324). User-level config —",
      "# [otel] is ignored in project-local config.toml.",
  ]
  if spec.privacy == "replay":
    lines += [
        "# Replay tier requested: NOT offered for Codex — Codex documents",
        "# no supported raw request/response body path, so prompt capture",
        "# stays off.",
    ]
  lines += [
      "[otel]",
      'environment = "prod"',
      'exporter = "otlp-http"',
      '# PENDING #317: metrics_exporter/trace_exporter stay "none" until the',
      "# version-specific Codex config shape is pinned and verified.",
      'metrics_exporter = "none"',
      'trace_exporter = "none"',
      "log_user_prompt = false",
      "",
      '[otel.exporter."otlp-http"]',
      f'endpoint = "{spec.endpoint}/v1/logs"',
      'protocol = "binary"',
      'headers = { "Authorization" = "Bearer ${BQAA_OTLP_TOKEN}" }',
  ]
  return "\n".join(lines) + "\n"


def endpoint_managed_guidance(spec: BootstrapSpec, source: str) -> str:
  """MDM deployment guidance for the generated managed-settings artifact."""
  del spec  # guidance is tier-independent; the JSON artifact carries tiers
  return f"""# Deploying {source} managed settings

Two distribution paths (issue #324):

## Server-managed settings (recommended)

There is **no admin API** for server-managed settings: an Owner/Primary
Owner pastes the generated `{source}.managed-settings.json` contents into
the Claude admin console (Settings -> Claude Code -> managed settings).

## Endpoint-managed settings (MDM / OS policy)

Deploy `{source}.managed-settings.json` to each machine as
`managed-settings.json`:

* **macOS** — install to
  `/Library/Application Support/ClaudeCode/managed-settings.json` via your
  MDM (e.g. a Jamf/Kandji package or a configuration profile that writes
  the file). A LaunchDaemon is not required; the file is read on startup.
* **Windows** — install to
  `C:\\ProgramData\\ClaudeCode\\managed-settings.json` via Intune
  (Win32 app or PowerShell script deployment) or Group Policy file
  preferences.

The bearer token in the file grants write access to your telemetry
endpoint — treat the artifact as a secret and prefer your MDM's secure
file distribution.
"""


def render_artifacts(
    spec: BootstrapSpec, sources: tuple[str, ...]
) -> dict[str, str]:
  """Render ``{filename: content}`` for the requested telemetry sources."""
  for source in sources:
    if source not in SOURCES:
      raise ValueError(f"unknown source {source!r}; expected one of {SOURCES}")
  artifacts: dict[str, str] = {}
  if "claude-code" in sources:
    artifacts["claude-code.managed-settings.json"] = (
        json.dumps(claude_code_managed_settings(spec), indent=2) + "\n"
    )
    artifacts["claude-code.endpoint-managed.md"] = endpoint_managed_guidance(
        spec, "claude-code"
    )
  if "codex" in sources:
    artifacts["codex.config.toml"] = codex_config_toml(spec)
  return artifacts
