CREATE TABLE IF NOT EXISTS `test-project-0728-467323.context_graph.agent_session` (agent_session_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.context_graph.business_constraint` (business_constraint_id STRING, constraint_type STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.context_graph.candidate` (candidate_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.context_graph.constraint_application` (constraint_application_id STRING, constraint_result STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.context_graph.context_snapshot` (context_snapshot_id STRING, snapshot_payload STRING, snapshot_timestamp TIMESTAMP, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.context_graph.decision_execution` (decision_execution_id STRING, business_entity_id STRING, latency_ms INT64, span_id STRING, trace_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.context_graph.decision_point` (decision_point_id STRING, reversibility STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.context_graph.outcome_signal` (outcome_signal_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.context_graph.rejection_reason` (rejection_reason_id STRING, rejection_category STRING, rejection_text STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.context_graph.reward_computation` (reward_computation_id STRING, reward_value FLOAT64, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.context_graph.selection_outcome` (selection_outcome_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.context_graph.applied_constraint` (constraint_application_id STRING, business_constraint_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.context_graph.at_context_snapshot` (decision_execution_id STRING, context_snapshot_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.context_graph.derived_reward` (reward_computation_id STRING, outcome_signal_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.context_graph.evaluates_candidate` (decision_point_id STRING, candidate_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.context_graph.evolved_from` (src_decision_execution_id STRING, dst_decision_execution_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.context_graph.executed_at_decision_point` (decision_execution_id STRING, decision_point_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.context_graph.filtered_by_constraint` (candidate_id STRING, constraint_application_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.context_graph.has_rejection_reason` (candidate_id STRING, rejection_reason_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.context_graph.has_selection_outcome` (decision_execution_id STRING, selection_outcome_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.context_graph.part_of_session` (decision_execution_id STRING, agent_session_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.context_graph.produced_outcome` (decision_execution_id STRING, outcome_signal_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.context_graph.rejected_candidate` (selection_outcome_id STRING, candidate_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.context_graph.selected_candidate` (selection_outcome_id STRING, candidate_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.context_graph.superseded_by` (src_decision_execution_id STRING, dst_decision_execution_id STRING, session_id STRING, extracted_at TIMESTAMP);
